Refactor login/signup wordpress
doofinder/doofinder-wordpress pull request #62
Opened 2023-05-31 11:02 UTC by eduardogomez97

Required by: https://github.com/orgs/doofinder/projects/19/views/6?pane=issue&itemId=24897210

2023-06-06 14:47 UTC, pedromcp90 requested changes

2023-06-06 14:47 UTC, pedromcp90 commented on doofinder/includes/class-setup-wizard.php
> +		ob_start();
```suggestion
		ob_start();
		?>
		<div class="notice notice-success is-dismissible">
			<div id="message" class="wordpress-message doofinder-notice-setup-wizard">
				<figure class="logo" style="width:5rem;height:auto;float:left;margin:.5em 0;margin-right:0.75rem;">
					<img src="<?php echo Doofinder_For_WordPress::plugin_url() . 'assets/svg/imagotipo1.svg'; ?>" />
				</figure>
				<h3><?php echo $message_intro;?></h3>
				<p><?php echo $message;?></p>
				<p class="submit">
					<a href="<?php echo self::get_url(); ?>" class="button-primary button-setup-wizard"><?php _e('Setup Wizard', 'wordpress-doofinder'); ?></a>
					<?php if ($settings) : ?>
						&nbsp;<a class="button-secondary button-settings" href="<?php echo Settings::get_url(); ?>"><?php _e('Settings', 'wordpress-doofinder'); ?></a>
					<?php endif; ?>
				</p>
			</div>
		</div>
		<?php
		$html = ob_get_clean();
		return $html;
```

2023-06-06 14:47 UTC, pedromcp90 commented on doofinder/views/wizard.php
> +    <title><?php printf(__('%s - Doofinder Setup Wizard', 'woocommerce-doofinder'), get_bloginfo('name')); ?></title>
```suggestion
    <title><?php printf(__('%s - Doofinder Setup Wizard', 'wordpress-doofinder'), get_bloginfo('name')); ?></title>

```

2023-06-06 14:54 UTC, pedromcp90 commented
Please add this missing file that is needed to be shown in the Wizard setup notice.
`/assets/svg/imagotipo1.svg`

2023-06-06 16:10 UTC, pedromcp90 commented
The create-store endpoint used by the Wizard Setup is failing.
You should check whether it is a payload issue or something wrong in doofapi or doomanager.

2023-06-09 08:44 UTC, pedromcp90 approved these changes

2023-06-20 16:08 UTC, eduardogomez97 commented
This has already been merged into the refactor branch

2023-06-20 16:08 UTC, closed without merging